/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wang_jnisample_App */

#ifndef _Included_com_wang_jnisample_App
#define _Included_com_wang_jnisample_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wang_jnisample_App
 * Method:    jniSetAppInfo
 * Signature: (Lcom/wang/jnisample/AppInfo;)V
 */
JNIEXPORT void JNICALL Java_com_wang_jnisample_App_jniSetAppInfo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wang_jnisample_App
 * Method:    jniGetAppInfo
 * Signature: ()Lcom/wang/jnisample/AppInfo;
 */
JNIEXPORT jobject JNICALL Java_com_wang_jnisample_App_jniGetAppInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
